import { rm } from 'node:fs/promises';
import path from 'node:path';

/**
 * Runs once after the whole suite. Removes the auth storage state generated by
 * the setup project so stale tokens never leak into a later run.
 */
async function globalTeardown(): Promise<void> {
  const authDir = path.resolve('.playwright/auth');
  await rm(authDir, { recursive: true, force: true });
}

export default globalTeardown;
